### ISSUE TITLE
Failed to activate the autocomplete-latex-cite package

### ISSUE THREAD

**Issue by mmuaz95** [hesstobi/atom-autocomplete-latex-cite#19] opened 2019-06-29 13:05 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.13.6
**Thrown From**: [autocomplete-latex-cite](https://github.com/hesstobi/atom-autocomplete-latex-cite) package 0.3.2

### Stack Trace

Failed to activate the autocomplete-latex-cite package

```
At Cannot find module './ts-compiled/command-aliases'

Error: Cannot find module './ts-compiled/command-aliases'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155156)
    at Module.require (/app.asar/static/index.js:53:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146462)
    at /packages/autocomplete-latex-cite/node_modules/latex-to-unicode-converter/index.js:6:10)
    at /packages/autocomplete-latex-cite/node_modules/latex-to-unicode-converter/index.js:17:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146462)
    at /packages/autocomplete-latex-cite/lib/lite-bibtex-parse.js:32:31)
    at /packages/autocomplete-latex-cite/lib/lite-bibtex-parse.js:373:40)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146462)
    at /packages/autocomplete-latex-cite/lib/cite-manager.coffee:7:15)
    at /packages/autocomplete-latex-cite/lib/cite-manager.coffee:1:1)
    at /packages/autocomplete-latex-cite/lib/cite-manager.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147172)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-json 5.5.2 
autocomplete-latex-cite 0.3.2 
docker 0.8.0 
gpp-compiler 3.0.7 
language-latex 1.2.0 
latex 0.50.2 
latex-autocomplete 1.1.1 
pdf-view 0.71.0 
```

**Comment by bbbrumley** [comment] 2019-07-07 07:50
This is a duplicate of #18

**Comment by hesstobi** [comment] 2019-12-02 16:29
Fixed in version v0.3.4

**Closed by hesstobi** 2019-12-02 16:29 UTC

**Comment by mmmikemon** [comment] 2020-03-22 18:52
I am also having this exact problem, on the most recent versions of atom and autocomplete-latex-cite:

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.3
**Thrown From**: [autocomplete-latex-cite](https://github.com/hesstobi/atom-autocomplete-latex-cite) package 0.3.5


### Stack Trace

Failed to activate the autocomplete-latex-cite package

```
At Total of weights cannot exceed 1

Error: Total of weights cannot exceed 1
    at e.value (/packages/autocomplete-bibtex/node_modules/fuse.js/dist/fuse.js:9:3409)
    at /packages/autocomplete-bibtex/node_modules/fuse.js/dist/fuse.js:9:2634)
    at /packages/autocomplete-latex-cite/lib/cite-manager.coffee:41:13)
    at /packages/autocomplete-latex-cite/lib/cite-provider.coffee:12:16)
    at Object.provide (/packages/autocomplete-latex-cite/lib/main.coffee:21:19)
    at Package.activateServices (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3224971)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3222013)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2607)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1214120)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1215561)
    at PackageManager.triggerDeferredActivationHooks (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382896)
    at activatePromise.Promise.all.then (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:381647)
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-beautify 0.33.4 
atom-python-run 0.9.7 
autocomplete-latex-cite 0.3.5 
busy-signal 2.0.1 
ex-mode 0.18.0 
Hydrogen 2.14.1 
hydrogen-python 0.0.8 
hydrogen-run 0.1.1 
ide-python 1.5.0 
intentions 1.1.5 
language-fortran 2.1.10 
language-latex 1.2.0 
latex 0.50.2 
linter 2.3.1 
linter-gfortran 1.0.0 
linter-spell 0.15.0 
linter-spell-latex 0.11.0 
linter-ui-default 1.8.1 
python-tools 0.6.9 
vim-mode-plus 1.36.4 
vim-mode-plus-macros 0.1.2 
```

**Comment by holgerreich** [comment] 2020-04-01 16:20
Same problem on freshly installed atom here.


[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.4
**Thrown From**: [autocomplete-latex-cite](https://github.com/hesstobi/atom-autocomplete-latex-cite) package 0.3.5


### Stack Trace

Failed to activate the autocomplete-latex-cite package

```
At Total of weights cannot exceed 1

Error: Total of weights cannot exceed 1
    at e.value (/packages/autocomplete-latex-cite/node_modules/fuse.js/dist/fuse.js:9:3409)
    at /packages/autocomplete-latex-cite/node_modules/fuse.js/dist/fuse.js:9:2634)
    at /packages/autocomplete-latex-cite/lib/cite-manager.coffee:41:13)
    at /packages/autocomplete-latex-cite/lib/cite-provider.coffee:12:16)
    at Object.provide (/packages/autocomplete-latex-cite/lib/main.coffee:21:19)
    at Package.activateServices (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3224971)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3222013)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2607)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1214120)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1215561)
    at PackageManager.triggerActivationHook (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:383200)
    at Workspace.handleGrammarUsed (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:434456)
    at TextEditor.observeGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:7983)
    at onDidAddPaneItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:426560)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1214120)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1215561)
    at PaneContainer.didAddPaneItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:446613)
    at Pane.addItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:459024)
    at Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:457887)
    at Workspace.open (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:431601)
```

### Commands

```
  3x -2:41.8.0 pdf-view:zoom-in (div.pdf-view)
```

### Non-Core Packages

```
autocomplete-latex-cite 0.3.5 
autocomplete-latex-references 0.3.2 
language-latex 1.2.0 
latex 0.50.2 
latex-autocomplete 1.1.1 
markdown-pdf 2.3.2 
pdf-view 0.72.0 
pen-paper-coffee-syntax 0.17.0 
sync-settings 4.3.2 
```

**Comment by jmague** [comment] 2020-08-07 07:34
So do I...

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.6
**Thrown From**: [autocomplete-latex-cite](https://github.com/hesstobi/atom-autocomplete-latex-cite) package 0.3.5


### Stack Trace

Failed to activate the autocomplete-latex-cite package

```
At Total of weights cannot exceed 1

Error: Total of weights cannot exceed 1
    at e.value (/packages/autocomplete-latex-references/node_modules/fuse.js/dist/fuse.js:9:3409)
    at /packages/autocomplete-latex-references/node_modules/fuse.js/dist/fuse.js:9:2634)
    at /packages/autocomplete-latex-cite/lib/cite-manager.coffee:41:13)
    at /packages/autocomplete-latex-cite/lib/cite-provider.coffee:12:16)
    at Object.provide (/packages/autocomplete-latex-cite/lib/main.coffee:21:19)
    at Package.activateServices (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3195623)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3192665)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1201500)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1202941)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:383233
    at Set.forEach (<anonymous>)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:383195)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:926825
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:921431)
    at n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1063432)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1063638)
    at ChildProcess.emit (events.js:194:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
autocomplete-latex 1.0.0 
autocomplete-latex-cite 0.3.5 
autocomplete-latex-references 0.3.2 
busy-signal 2.0.1 
intentions 1.1.5 
language-latex 1.2.0 
latex 0.50.2 
latex-autocomplete 1.1.1 
linter 2.3.1 
linter-markdown 5.2.11 
linter-spell 0.15.0 
linter-spell-latex 0.11.0 
linter-ui-default 1.8.1 
notifications-plus 2.0.0 
```

**Comment by 73** [comment] 2020-09-07 12:46
[Enter steps to reproduce:]

1. Load the Plugin

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Ubuntu 20.04.1
**Thrown From**: [autocomplete-latex-cite](https://github.com/hesstobi/atom-autocomplete-latex-cite) package 0.3.5


### Stack Trace

Failed to activate the autocomplete-latex-cite package

```
At Total of weights cannot exceed 1

Error: Total of weights cannot exceed 1
    at e.value (/packages/autocomplete-latex-references/node_modules/fuse.js/dist/fuse.js:9:3409)
    at /packages/autocomplete-latex-references/node_modules/fuse.js/dist/fuse.js:9:2634)
    at /packages/autocomplete-latex-cite/lib/cite-manager.coffee:41:13)
    at /packages/autocomplete-latex-cite/lib/cite-provider.coffee:12:16)
    at Object.provide (/packages/autocomplete-latex-cite/lib/main.coffee:21:19)
    at Package.activateServices (/usr/share/atom/resources/app/static/<embedded>:11:3193262)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:3190304)
    at /usr/share/atom/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1201460)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1202901)
    at /usr/share/atom/resources/app/static/<embedded>:11:383238
    at Set.forEach (<anonymous>)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/static/<embedded>:11:383200)
    at /usr/share/atom/resources/app/static/<embedded>:11:926785
    at r (/usr/share/atom/resources/app/static/<embedded>:11:921391)
    at n (/usr/share/atom/resources/app/static/<embedded>:14:1063432)
    at /usr/share/atom/resources/app/static/<embedded>:14:1063586
    at Socket.<anonymous> (/usr/share/atom/resources/app/static/<embedded>:14:1062188)
    at Socket.emit (events.js:199:15)
    at Pipe.<anonymous> (net.js:593:12)
```

### Commands

```
 51x -8:52.4.0 core:backspace (input.hidden-input)
     -7:45.1.0 core:move-left (input.hidden-input)
     -7:43.1.0 autocomplete-plus:confirm (input.hidden-input)
  4x -7:39.9.0 core:backspace (input.hidden-input)
  3x -7:06.0 core:move-down (input.hidden-input)
     -7:05.4.0 autocomplete-plus:confirm (input.hidden-input)
     -7:04.7.0 intentions:highlight (input.hidden-input)
     -7:04.7.0 core:save (input.hidden-input)
     -3:30.4.0 intentions:highlight (input.hidden-input)
     -3:30.1.0 settings-view:open (input.hidden-input)
  2x -2:35.4.0 core:paste (input.hidden-input)
     -2:03.0 core:close (div.package-readme.native-key-bindings)
     -1:58.2.0 core:move-left (input.hidden-input)
     -1:57.2.0 core:move-up (input.hidden-input)
 20x -1:56.8.0 core:move-right (input.hidden-input)
     -1:55.5.0 core:move-down (input.hidden-input)
```

### Non-Core Packages

```
atom-animations 0.1.0 
autocomplete-latex-cite 0.3.5 
autocomplete-latex-references 0.3.2 
autocorrect 0.1.0 
autocorrect-en 0.0.3 
busy-signal 2.0.1 
dbclick-tree-view 1.6.3 
document-outline 2.1.2 
fancy-bracket-matcher 2.1.0 
file-icons 2.1.42 
git-blame 1.8.0 
gtk-dark-theme 0.1.4 
intentions 1.1.5 
language-docker 1.1.8 
language-ini 1.23.0 
language-latex 1.2.0 
language-markdown 0.37.0 
latex 0.50.2 
linter 2.3.1 
linter-chktex 1.4.0 
linter-ui-default 1.8.1 
open-unsupported-files 1.0.20 
outline-selection 0.3.2 
pigments 0.40.2 
rainbow-csv 1.4.0 
relative-numbers 0.9.1 
ruby-block 0.3.6 
todo-show 2.3.2 
typewriter-scroll 1.0.2 
```

**Comment by Fawkes83** [comment] 2021-06-29 19:26
I am also having this issue

`[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: DESKTOP-8EEF8IL
**Thrown From**: [autocomplete-latex-cite](https://github.com/hesstobi/atom-autocomplete-latex-cite) package 0.3.5


### Stack Trace

Failed to activate the autocomplete-latex-cite package

```
At Total of weights cannot exceed 1

Error: Total of weights cannot exceed 1
    at e.value (/packages/autocomplete-latex-references/node_modules/fuse.js/dist/fuse.js:9:3409)
    at /packages/autocomplete-latex-references/node_modules/fuse.js/dist/fuse.js:9:2634)
    at /packages/autocomplete-latex-cite/lib/cite-manager.coffee:41:13)
    at /packages/autocomplete-latex-cite/lib/cite-provider.coffee:12:16)
    at Object.provide (/packages/autocomplete-latex-cite/lib/main.coffee:21:19)
    at Package.activateServices (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:3512215)
    at Package.activateNow (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:3509257)
    at ~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1187631)
    at PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:385941)
    at ~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:384692
```

### Commands

```
```

### Non-Core Packages

```
atom-latex 0.9.1 
auto-save-on-idle 1.2.1 
autocomplete-bibtex 1.2.10 
autocomplete-latex 1.0.0 
autocomplete-latex-cite 0.3.5 
autocomplete-latex-references 0.3.2 
autocomplete-paths 2.15.2 
language-latex 1.2.0 
latex 0.50.2 
latex-autocomplete 1.1.1 
simple-drag-drop-text 0.5.0 
```
`
